### ISSUE TITLE
haphazard not hap-hazard

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-ajax-rest-refresher-readme#1]
Haphazard is one word, not hyphenated. Also, I would leave out the word "different" in this sentence:
"In 2000, Roy Thomas Fielding was frustrated by the hap-hazard different ways web applications were using the HTTP standard. "

Thank you.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe the issue to have been resolved.
